### ISSUE TITLE
How to install Docker EE so I can do the lab ...

### ISSUE THREAD

**Issue by emcpadden** [docker/dcus-hol-2017#26]
I was at DockerCon 2017 but did not have time to do the labs.  I was told that I could do the labs at home including the Docker EE labs.

To do the lab: Securing Apps with Docker EE Advanced / Docker Trusted Registry it says I have to install Docker EE.

I created some nodes on DigitalOcean and I usually use the curl command on get.docker.com to install docker but these install docker-ce.

How do I go about installing docker-ee on Digital Ocean so that I can do this lab?

Or is there another way to do this lab?

Thanks!!!
... Ed

**Comment by sixeyed** [comment]
Hi Ed - go to [Enterprise Editions on Docker Store](https://store.docker.com/search?offering=enterprise&type=edition). There are editions for Ubuntu, RHEL etc. - choose your edition and you can get a 1-month trial licence. The licence info gives you the install details.

**Comment by emcpadden** [comment]
Awesome! Thanks!!. Btw, dockercon was excellent!
