### ISSUE TITLE
Swarm Orchestration Advanced - chrch/docker-pets:latest

### ISSUE THREAD

**Issue by rogersass** [docker/dcus-hol-2017#27]
The image chrch/docker-pets:latest does not exist. Update with chrch/docker-pets:2.0. (Image with tag "latest" is not in the repo).

**Comment by mark-church** [comment]
Hi @rogersass, I deleted the `latest` tag and replaced `latest` in the lab with explicit tags `1.0` and `2.0`. I don't believe `latest` is referenced in the lab anymore.

**Comment by rogersass** [comment]
Hi @mark-church thank you for updating the lab. I see the "latest" tag is no longer referenced.
